### ISSUE TITLE
invalid table name in install.xml

### ISSUE THREAD

**Issue by danmarsden** [willianmano/moodle-block_myprogress#12]
the table name "myprogress_course_progress" is not correct - all table names must use the frankenstyle naming convention as per:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#table-names

note this is a blocker for plugins db approval.

**Comment by luiggisanso** [comment]
Hi @danmarsden 

I'll take a look,

**Comment by luiggisanso** [comment]
Done, waiting @willianmano aprobation ;-)

**Comment by willianmano** [comment]
@luiggisanso approved!
