### ISSUE TITLE
missing privacy api.

### ISSUE THREAD

**Issue by danmarsden** [willianmano/moodle-block_myprogress#13]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API 

This is not a blocker for plugins db approval.

**Comment by luiggisanso** [comment]
Hi @danmarsden 

Done in my fork, waiting merge ;-)

**Comment by luiggisanso** [comment]
@danmarsden @willianmano 

what about this string for privacy:metadata :
The block only displays existing completion data

Is it correct ?
plugin has only userid and user progress

Do I change provider.php with a specific collection ?

**Comment by luiggisanso** [comment]
I put here my ideas for my next job ;-)

```
[ ] use context_course;
[ ] use core_privacy\local\request\userlist;
```

```
[ ]     \core_privacy\local\metadata\provider,
[ ]     \core_privacy\local\request\plugin\provider,
[ ]     \core_privacy\local\request\core_userlist_provider ,
```

```

[ ]   public static function _get_metadata(collection $collection) {
        $collection->add_database_table('block_myprogress', [
            'myprogress' => 'privacy:metadata:myprogress:myprogress',
            'userid' => 'privacy:metadata:myprogress:userid',
        ], 'privacy:metadata:myprogress');
       return $collection;
    }
```

Or something like that...

**Comment by danmarsden** [comment]
unfortunately you can't use the null provider because the block_myprogress_course table contains a userid field which needs to be covered in the delete and export parts of the privacy api.

Moodle has some unit tests that makes sure the _get_metadata function includes coverage for those tables, but you should also be handling the delete and export components for full compliance with the privacy class.

thanks!

**Comment by luiggisanso** [comment]
Hi @danmarsden and @willianmano 

I worked hard to find -maybe- the good way to add a real privacy for this block, following other plugins and documentations.

I hope I'm on the right way ;-)

Now, the block is listed in pluginregistry with this result :

![image](https://github.com/willianmano/moodle-block_myprogress/assets/1565841/063637d7-c6d0-454a-a517-40dc92c38dbc)

A user can export and delete his data too.

Could you check my fork before I merge here, or PR must be done to check the new version ?

**Comment by danmarsden** [comment]
hey @luiggisanso once something has been approved in the plugins db, the review team don't tend to do any further reviews on that plugin - you just take control over when you want to release new versions in the plugins db on your own!

**Comment by luiggisanso** [comment]
Ok @danmarsden it's logical
I'll PR and let see with @willianmano 

Thanks
