### ISSUE TITLE
Create a setting to select which cohorts to show progress

### ISSUE THREAD

**Issue by willianmano** [willianmano/moodle-block_myprogress#2]
Regarding the cohorts, I know that they are groups in moodle context. And I know that the use of cohorts is very variable.

In most cases that I see (95%) when a cohort synchronization is done, it is for a "pedagogical" use to synchronize participants in a course (promotion or class, study level, training session, subject…).

And in the vast majority, cohorts are also used outside of courses for other filters or statistics or groupings (job cohort, function, location...)
And these are never (rarely) used in the courses. For specific content (with filter codes), or a specific theme why not.

For me, it makes no sense to display all the cohorts of a user in the course, if the cohort is not used in the course.
One should only have the "pedagogical" cohorts that are used as enrolment methods.

## An idea for improvement

When you look at https://moodle.org/plugins/block_cohortspecifichtmlblock, it lists all available cohorts but allows you to select the ones you want.

Wouldn't this be a solution to cover all cases?
Can we add this form in block settings?

(https://github.com/moodle-an-hochschulen/moodle-block_cohortspecifichtml/blob/master/edit_form.php line 59)

**Comment by luiggisanso** [comment]
Hi @willianmano 

Works as expected, great ! 👍
