### ISSUE TITLE
Reorder list to have "Class Average" at the bottom (end) of the block

### ISSUE THREAD

**Issue by luiggisanso** [willianmano/moodle-block_myprogress#3]
Hi @willianmano 

My first request was to reorder the list of averages.

To have the list from the smallest to the largest (single, group, cohort, class) like this :
![image](https://user-images.githubusercontent.com/1565841/222919309-69219f45-de8b-4c57-8899-fa809f2b546f.png)

I just moved the lines 8-13 to the bottom from /myprogress/templates/block.mustache in my moodle instance
I don't know if that's enought for the plugin integrity, but it semmes to be ok.

Not wanting to modify the code directly in this plugin repository, I'll let you do properly ;-D

Cheers.

**Comment by willianmano** [comment]
Gotcha! Yeah, we just need to move the code in mustache templates.
