### ISSUE TITLE
Adding French translation

### ISSUE THREAD

**Issue by luiggisanso** [willianmano/moodle-block_myprogress#4]
Hi @willianmano 

We can add french translation here, until AMOS integration ;-)

How can I do ?

Do I create a new folder directcly in this repo ?

I have the PHP file but I can't attach it here

And later, we have to think about some help strings ;-)

**Comment by willianmano** [comment]
Hi @luiggisanso 

You can clone the repo, add the folder and the file and submit a Pull Request.

You can also send me the file via email, but by sending the Pull Request you will appear as a contributor of the project. :)
